name: nnls_mc
type: monte_carlo
learning_rate: 0.01
batch_size: 128
feature_extractor:
  type: policy_representation
  normalize: post
  policy_path: null
  algorithm: PPO
network:
  hidden_sizes: []
  activation: relu
