name: nnls_td
type: td
learning_rate: 0.001
target_update_rate: 0.1
feature_extractor:
  type: policy_representation
  normalize: post
  policy_path: null
  algorithm: PPO
network:
  hidden_sizes: []
  activation: relu
