name: nnls_td
type: td
learning_rate: 0.09
target_update_rate: 0.14
batch_size: 64
feature_extractor:
  type: policy_representation
  normalize: post
  policy_path: null
  algorithm: SAC
network:
  hidden_sizes: []
  activation: relu
