name: nnls_td
type: dqn
learning_rate: 0.09
target_update_rate: 0.003
batch_size: 64
feature_extractor:
  type: policy_representation
  normalize: post
  policy_path: null
  algorithm: PPO
network:
  hidden_sizes: []
  activation: relu
