name: least_squares_mc_rbf
type: least_squares_mc
learning_rate: 0.001
max_epochs: 1
ridge_lambda: 1.0e-6
feature_extractor:
  type: rbf
  normalize: false
  n_components: 100
  gamma: 1.0
  seed: 42
