name: nnls_td
type: dqn
learning_rate: 0.001
n_initializations: 1
max_epochs: 1
target_update_rate: 0.1
feature_extractor:
  type: policy_representation
  normalize: true
  policy_path: null
  algorithm: PPO
network:
  hidden_sizes: []
  activation: relu
